export default {
    REQUEST_DATE_END: 'REQUEST_DATE_END',
    RECEIVE_DATE_END: 'RECEIVE_DATE_END',
    CHANGE_REGISTER_KEY: 'CHANGE_REGISTER_KEY',
    VALIDATION_USER_INFO: 'VALIDATION_USER_INFO',
    VALIDATION_REGISTER_KEY: 'VALIDATION_REGISTER_KEY'
};