export default {
    REQUEST_DATE_END: 'REQUEST_DATE_END',
    RECEIVE_DATE_END: 'RECEIVE_DATE_END',
    CHANGE_REGISTER_KEY: 'CHANGE_REGISTER_KEY',
    VALIDATION_USER_INFO: 'VALIDATION_USER_INFO',
    VALIDATION_REGISTER_KEY: 'VALIDATION_REGISTER_KEY',
    VALIDATION_ERRORS_SHOW: 'VALIDATION_ERRORS_SHOW',
    CHANGE_REGISTER_STEP: 'CHANGE_REGISTER_STEP',
    ADD_PHOTO: 'ADD_PHOTO',
    DELETE_PHOTO: 'DELETE_PHOTO',
    DELETE_PHOTO_ITEM: 'DELETE_PHOTO_ITEM',
    CHANGE_PHOTO_KEY: 'CHANGE_PHOTO_KEY',
    SET_PHOTO_ACTIVE: 'SET_PHOTO_ACTIVE',
    VALIDATION_PHOTO_KEY: 'VALIDATION_PHOTO_KEY:',
    SAVE_USER_REQUEST: 'SAVE_USER_REQUEST',
    SAVE_USER_COMPLETE: 'SAVE_USER_COMPLETE',
    SAVE_PHOTO_NUMBER: 'SAVE_PHOTO_NUMBER'
};