export default {
    REQUEST_ITEMS: 'REQUEST_ITEMS',
    RECEIVE_ITEMS: 'RECEIVE_ITEMS',
    REQUEST_SUBITEMS: 'REQUEST_SUBITEMS',
    RECEIVE_SUBITEMS: 'RECEIVE_SUBITEMS',
    REQUEST_ITEM_RESULT: 'REQUEST_ITEM_RESULT',
    RECEIVE_ITEM_RESULT: 'RECEIVE_ITEM_RESULT',
    SET_ITEM_ACTIVE: 'SET_ITEM_ACTIVE',
    SET_MODIFY: 'SET_MODIFY',
    CHANGE_ITEMS_KEY: 'CHANGE_ITEM_KEY'
};