export default {
    ITEMS_REQUEST: 'JURY_ITEMS_REQUEST',
    ITEMS_RECEIVE: 'JURY_ITEMS_RECEIVE',
    RATING_REQUEST: 'RATING_REQUEST',
    RATING_RECEIVE: 'RATING_RECEIVE',
    RATING_UPDATE: 'RATING_UPDATE',
    RATING_UPDATE_COMPLETE: 'RATING_UPDATE_COMPLETE',
    CHANGE_ACTIVE_CATEGORY: 'CHANGE_ACTIVE_CATEGORY',
    SET_MODAL: 'SET_MODAL',
    SET_MODAL_IMG: 'SET_MODAL_IMG',
    COMMENT_ACTIVE: 'COMMENT_ACTIVE',
    CHANGE_COMMENT: 'CHANGE_COMMENT',
    REQUEST_DATE_END: 'VOTE_DATE_END_REQUEST',
    RECEIVE_DATE_END: 'VOTE_DATE_END_RECEIVE'
};